# Generated by Django 4.1.4 on 2023-01-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
